services:
  redis:
    image: redis/redis-stack:latest
    container_name: ihatesheets-redis
    ports:
      - "6379:6379"
      - "5540:8001"
    volumes:
      - redis-data:/data
    restart: always

volumes:
  redis-data:
